### PR TITLE
add two themes

### PR DESCRIPTION
**Pull request by zhouhua**
I tried adding a few different title styles.

1. flat (default)

image

2. blur (I mentioned this to you a few days ago.)

image

3. float (Inspired by #20)

image

### CODE REVIEW

**Comment by itsonlyjames** [comment]
I especially love the float theme! Should we create a Style Settings configurable option for background colour? Because I wonder if a white background, but a coloured border could also look really nice, almost like a pill element. 

I have some ideas for the blur theme also, as it's slightly jarring with the hard edges. I will find some time to add some adjustments soon. 

Side note: add a setting for enabling/disabling the icons, this will go well alongside the theme choices (what do you think the source edit mode should do, remove the hashes also?). I manually remove them from my local code and set the indent to 0, which mimics the VSCode functionality and allows the hashes to "indent" the items.

**Comment by zhouhua** [comment]
1. Of course, we can add style settings configuration options to modify the theme styles.
2. I also care about the hard edges of the backdrop: blur effect, but I haven't found a good solution. If you have a way to handle it, that would be fantastic. I even think that if you have other style ideas, you could add new themes as well.
3. I have already agreed to add a setting for enabling/disabling the icons in #8. However, since we refactored the UI implementation, this part of the logic needs to be re-implemented. (By the way, should we close #8 and re-implement it based on the Svelte approach?)
4. Other points, such as disabling indentation and displaying # in source mode, can all be controlled through settings options.

**Comment by itsonlyjames** [comment]
For sure close that PR, it's completely outdated now. We can implement a similar solution within the new framework. It's only classes I'm adding and icons I'm hiding. Easy enough. I've set it up to be hooked into a setting later. 

Need to setup an option for display # in source mode.

**Comment by itsonlyjames** [comment]
@zhouhua I softened the edges on the blur style. Let me know your thoughts. 

We also ought to make the background colour for the float style a style-setting also 👍 After that, it's good to go!

**Pull request merged**
